# Changes to 'enablePlugin' will require the plugin to be reloaded.
# -
# delay value is the ticks waiting until the blocks starts to regenerate
# period value is the ticks waiting for each individual blocks regenerating
# 20 Ticks = 1 Seconds
# -
# Add your worlds under the 'words:' list options to allow blocks to regenerate in those worlds
# -
# TnTs' & Creepers' explosion meeting a trigger circumstance will permanently do block damage  (blocks will not regen)
# -
# Visit https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html for a list of particles to use from (not case sensitive here)
enablePlugin: true

enableTnTRegen: true
enableCreeperRegen: true
instantRegen: false
disableExplosionBlockDamage: false
enableParticles: true
delayTnT: 1200
periodTnT: 20

delayCreeper: 1200
periodCreeper: 20

particle: heart
worlds:
- world

triggers:
  minY: 0.0
  maxY: 256.0
